Repository easifem/classes, pull requests merged in 2025-05, with the labels that each got.

#517 Making some adjustment to compile easifem without plplot support.
  src/modules/EasyPlplot/CMakeLists.txt
  src/modules/EasyPlplot/src/EasyPlplot.F90
  src/modules/PLPlot/CMakeLists.txt
  src/modules/Plot/src/Plot_Method.F90
  src/submodules/PLPlot/CMakeLists.txt
Labels: bug

#516 Cleaning in Classes
  src/modules/CMakeLists.txt
  src/modules/ElastoDynamics2DFEM/CMakeLists.txt
  src/modules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class.F90
  src/modules/ScalarWave2DFEM/CMakeLists.txt
  src/modules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class.F90
  src/modules/ScalarWave2DSTFEM/CMakeLists.txt
  src/modules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class.F90
  src/modules/ScalarWave2DSTFEM/src/TDGAlgoParam.F90
  src/submodules/CMakeLists.txt
  src/submodules/ElastoDynamics2DFEM/CMakeLists.txt
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@ApplyDirichletBCMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@AssembleMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@ConstructorMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@IOMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@RunMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@SetMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@SolveMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@UpdateMethods.F90
  src/submodules/ElastoDynamics2DFEM/src/ElastoDynamics2DFEM_Class@WriteDataMethods.F90
  src/submodules/ScalarWave2DFEM/CMakeLists.txt
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@ApplyDirichletBCMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@AssembleMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@ConstructorMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@IOMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@RunMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@SetMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@SolveMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@UpdateMethods.F90
  src/submodules/ScalarWave2DFEM/src/ScalarWave2DFEM_Class@WriteDataMethods.F90
  src/submodules/ScalarWave2DSTFEM/CMakeLists.txt
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@ApplyDirichletBCMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@AssembleMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@ConstructorMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@IOMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@RunMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@SetMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@SolveMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@UpdateMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/ScalarWave2DSTFEM_Class@WriteDataMethods.F90
  src/submodules/ScalarWave2DSTFEM/src/TDGAlgoParam@Methods.F90
Labels: kernels

#519 Clean use association in Plplot related modules
  src/modules/PLPlot/src/PLPlot_Class.F90
  src/submodules/PLPlot/src/PLPlot_Class@BarMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@ColorbarMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@ConstructorMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@ContourMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@FillMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@LinePlotMethods copy.F90
  src/submodules/PLPlot/src/PLPlot_Class@LinePlotMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@PlotMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@QuiverMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@ScatterMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@SetMethods.F90
  src/submodules/PLPlot/src/PLPlot_Class@SurfaceMethods.F90
Labels: plplot

#521 Adding GetValue method in tomlutility for boolean
  src/modules/Toml/src/TomlUtility.F90
  src/submodules/Toml/src/TomlUtility@GetMethods.F90
Labels: enhancement, toml

#522 Updates in GnuPlot
  src/submodules/GnuPlot/src/GnuPlot_Class@PlotMethods.F90
Labels: enhancement, plotting
